// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uizatcahxcyscjbkxnzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpemF0Y2FoeGN5c2NqYmt4bnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjA2OTAsImV4cCI6MjA2NjQzNjY5MH0._u0W7P-j1tpBvgv5ruNwL__hzmfyVSBfk4V9H4NL3Y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);